use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Users::Table)
                    .col(ColumnDef::new(Users::Id).text().not_null().primary_key())
                    .col(ColumnDef::new(Users::EmailNormalized).text().not_null())
                    .col(ColumnDef::new(Users::EmailDisplay).text().not_null())
                    .col(ColumnDef::new(Users::Role).text().not_null().check((
                        "ck_users_role",
                        Expr::col(Users::Role).is_in(["user", "superuser"]),
                    )))
                    .col(ColumnDef::new(Users::Status).text().not_null().check((
                        "ck_users_status",
                        Expr::col(Users::Status).is_in([
                            "pending_verification",
                            "active",
                            "disabled",
                            "deleting",
                        ]),
                    )))
                    .col(
                        ColumnDef::new(Users::AuthVersion)
                            .integer()
                            .not_null()
                            .default(0)
                            .check((
                                "ck_users_auth_version",
                                Expr::col(Users::AuthVersion).gte(0),
                            )),
                    )
                    .col(ColumnDef::new(Users::EmailVerifiedAt).text())
                    .col(ColumnDef::new(Users::CreatedAt).text().not_null())
                    .col(ColumnDef::new(Users::UpdatedAt).text().not_null())
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_users_email_normalized")
                    .table(Users::Table)
                    .col(Users::EmailNormalized)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(PasswordCredentials::Table)
                    .col(
                        ColumnDef::new(PasswordCredentials::UserId)
                            .text()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(PasswordCredentials::PasswordHash)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PasswordCredentials::PepperKeyId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PasswordCredentials::CreatedAt)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PasswordCredentials::UpdatedAt)
                            .text()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_password_credentials_user")
                            .from_tbl(PasswordCredentials::Table)
                            .from_col(PasswordCredentials::UserId)
                            .to_tbl(Users::Table)
                            .to_col(Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AuthSessions::Table)
                    .col(
                        ColumnDef::new(AuthSessions::Id)
                            .text()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(AuthSessions::UserId).text().not_null())
                    .col(
                        ColumnDef::new(AuthSessions::Transport)
                            .string_len(32)
                            .not_null()
                            .check((
                                "ck_auth_sessions_transport",
                                Expr::col(AuthSessions::Transport)
                                    .is_in(["browser_cookie", "bearer"]),
                            )),
                    )
                    .col(
                        ColumnDef::new(AuthSessions::SecretDigest)
                            .blob()
                            .not_null()
                            .check((
                                "ck_auth_sessions_secret_digest",
                                Expr::cust("length(secret_digest) = 32"),
                            )),
                    )
                    .col(ColumnDef::new(AuthSessions::CsrfDigest).blob().check((
                        "ck_auth_sessions_csrf_digest",
                        Expr::cust("csrf_digest IS NULL OR length(csrf_digest) = 32"),
                    )))
                    .col(
                        ColumnDef::new(AuthSessions::KeyId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthSessions::AuthVersion)
                            .integer()
                            .not_null()
                            .check((
                                "ck_auth_sessions_auth_version",
                                Expr::col(AuthSessions::AuthVersion).gte(0),
                            )),
                    )
                    .col(
                        ColumnDef::new(AuthSessions::AuthenticatedAt)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AuthSessions::CreatedAt).text().not_null())
                    .col(ColumnDef::new(AuthSessions::LastSeenAt).text().not_null())
                    .col(ColumnDef::new(AuthSessions::IdleExpiresAt).text().not_null())
                    .col(
                        ColumnDef::new(AuthSessions::AbsoluteExpiresAt)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AuthSessions::RevokedAt).text())
                    .col(ColumnDef::new(AuthSessions::RevocationReason).string_len(128))
                    .col(ColumnDef::new(AuthSessions::UserAgent).string_len(256))
                    .check((
                        "ck_auth_sessions_transport_csrf",
                        Expr::cust(
                            "(transport = 'browser_cookie' AND csrf_digest IS NOT NULL) OR (transport = 'bearer' AND csrf_digest IS NULL)",
                        ),
                    ))
                    .check((
                        "ck_auth_sessions_expiry",
                        Expr::cust("idle_expires_at <= absolute_expires_at"),
                    ))
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_auth_sessions_user")
                            .from_tbl(AuthSessions::Table)
                            .from_col(AuthSessions::UserId)
                            .to_tbl(Users::Table)
                            .to_col(Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        for index in [
            Index::create()
                .name("idx_auth_sessions_user_active")
                .table(AuthSessions::Table)
                .col(AuthSessions::UserId)
                .col(AuthSessions::RevokedAt)
                .to_owned(),
            Index::create()
                .name("idx_auth_sessions_idle_expires_at")
                .table(AuthSessions::Table)
                .col(AuthSessions::IdleExpiresAt)
                .to_owned(),
            Index::create()
                .name("idx_auth_sessions_absolute_expires_at")
                .table(AuthSessions::Table)
                .col(AuthSessions::AbsoluteExpiresAt)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(OauthClients::Table)
                    .col(
                        ColumnDef::new(OauthClients::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OauthClients::Issuer)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OauthClients::ClientName).string_len(128))
                    .col(
                        ColumnDef::new(OauthClients::ApplicationType)
                            .string_len(8)
                            .not_null()
                            .check((
                                "ck_oauth_clients_application_type",
                                Expr::col(OauthClients::ApplicationType).is_in(["native", "web"]),
                            )),
                    )
                    .col(
                        ColumnDef::new(OauthClients::GrantTypes)
                            .string_len(256)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthClients::ResponseTypes)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthClients::Scope)
                            .string_len(512)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthClients::TokenEndpointAuthMethod)
                            .string_len(16)
                            .not_null()
                            .default("none")
                            .check((
                                "ck_oauth_clients_public",
                                Expr::col(OauthClients::TokenEndpointAuthMethod).eq("none"),
                            )),
                    )
                    .col(
                        ColumnDef::new(OauthClients::CreatedAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_oauth_clients_id_issuer")
                    .table(OauthClients::Table)
                    .col(OauthClients::Id)
                    .col(OauthClients::Issuer)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(OauthClientRedirectUris::Table)
                    .col(
                        ColumnDef::new(OauthClientRedirectUris::ClientId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthClientRedirectUris::Issuer)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthClientRedirectUris::RedirectUri)
                            .string_len(2048)
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .name("pk_oauth_client_redirect_uris")
                            .col(OauthClientRedirectUris::ClientId)
                            .col(OauthClientRedirectUris::Issuer)
                            .col(OauthClientRedirectUris::RedirectUri),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_redirect_client")
                            .from_tbl(OauthClientRedirectUris::Table)
                            .from_col(OauthClientRedirectUris::ClientId)
                            .from_col(OauthClientRedirectUris::Issuer)
                            .to_tbl(OauthClients::Table)
                            .to_col(OauthClients::Id)
                            .to_col(OauthClients::Issuer)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(OauthAuthorizationCodes::Table)
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::SecretDigest)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::KeyId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::UserId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::ClientId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::Issuer)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::RedirectUri)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::RegisteredRedirectUri)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::Resource)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::Scope)
                            .string_len(512)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::AuthVersion)
                            .big_integer()
                            .not_null()
                            .check((
                                "ck_oauth_codes_auth_version",
                                Expr::col(OauthAuthorizationCodes::AuthVersion).gte(0),
                            )),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::CodeChallenge)
                            .string_len(43)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::CodeChallengeMethod)
                            .string_len(8)
                            .not_null()
                            .default("S256")
                            .check((
                                "ck_oauth_codes_pkce_method",
                                Expr::col(OauthAuthorizationCodes::CodeChallengeMethod).eq("S256"),
                            )),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::CreatedAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::ExpiresAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OauthAuthorizationCodes::ConsumedAt).string_len(64))
                    .col(
                        ColumnDef::new(OauthAuthorizationCodes::IssuedAccessTokenId).string_len(64),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_codes_user")
                            .from_tbl(OauthAuthorizationCodes::Table)
                            .from_col(OauthAuthorizationCodes::UserId)
                            .to_tbl(Users::Table)
                            .to_col(Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_codes_redirect")
                            .from_tbl(OauthAuthorizationCodes::Table)
                            .from_col(OauthAuthorizationCodes::ClientId)
                            .from_col(OauthAuthorizationCodes::Issuer)
                            .from_col(OauthAuthorizationCodes::RegisteredRedirectUri)
                            .to_tbl(OauthClientRedirectUris::Table)
                            .to_col(OauthClientRedirectUris::ClientId)
                            .to_col(OauthClientRedirectUris::Issuer)
                            .to_col(OauthClientRedirectUris::RedirectUri)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(OauthRefreshTokenFamilies::Table)
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::UserId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::ClientId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::Issuer)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::Resource)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::Scope)
                            .string_len(512)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::AuthVersion)
                            .big_integer()
                            .not_null()
                            .check((
                                "ck_oauth_refresh_families_auth_version",
                                Expr::col(OauthRefreshTokenFamilies::AuthVersion).gte(0),
                            )),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::CreatedAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokenFamilies::AbsoluteExpiresAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OauthRefreshTokenFamilies::RevokedAt).string_len(64))
                    .col(ColumnDef::new(OauthRefreshTokenFamilies::RevocationReason).string_len(32))
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_refresh_family_user")
                            .from_tbl(OauthRefreshTokenFamilies::Table)
                            .from_col(OauthRefreshTokenFamilies::UserId)
                            .to_tbl(Users::Table)
                            .to_col(Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_refresh_family_client")
                            .from_tbl(OauthRefreshTokenFamilies::Table)
                            .from_col(OauthRefreshTokenFamilies::ClientId)
                            .from_col(OauthRefreshTokenFamilies::Issuer)
                            .to_tbl(OauthClients::Table)
                            .to_col(OauthClients::Id)
                            .to_col(OauthClients::Issuer)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(OauthRefreshTokens::Table)
                    .col(
                        ColumnDef::new(OauthRefreshTokens::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokens::FamilyId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokens::SecretDigest)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokens::KeyId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokens::Generation)
                            .big_integer()
                            .not_null()
                            .check((
                                "ck_oauth_refresh_generation",
                                Expr::col(OauthRefreshTokens::Generation).gte(0),
                            )),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokens::CreatedAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthRefreshTokens::IdleExpiresAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OauthRefreshTokens::RotatedAt).string_len(64))
                    .col(ColumnDef::new(OauthRefreshTokens::RevokedAt).string_len(64))
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_refresh_token_family")
                            .from_tbl(OauthRefreshTokens::Table)
                            .from_col(OauthRefreshTokens::FamilyId)
                            .to_tbl(OauthRefreshTokenFamilies::Table)
                            .to_col(OauthRefreshTokenFamilies::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(OauthAccessTokens::Table)
                    .col(
                        ColumnDef::new(OauthAccessTokens::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::SecretDigest)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::KeyId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::UserId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::ClientId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::Issuer)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OauthAccessTokens::RedirectUri).string_len(2048))
                    .col(
                        ColumnDef::new(OauthAccessTokens::Resource)
                            .string_len(2048)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::Scope)
                            .string_len(512)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OauthAccessTokens::FamilyId).string_len(64))
                    .col(
                        ColumnDef::new(OauthAccessTokens::AuthVersion)
                            .big_integer()
                            .not_null()
                            .check((
                                "ck_oauth_tokens_auth_version",
                                Expr::col(OauthAccessTokens::AuthVersion).gte(0),
                            )),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::CreatedAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OauthAccessTokens::ExpiresAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OauthAccessTokens::RevokedAt).string_len(64))
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_tokens_user")
                            .from_tbl(OauthAccessTokens::Table)
                            .from_col(OauthAccessTokens::UserId)
                            .to_tbl(Users::Table)
                            .to_col(Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_tokens_redirect")
                            .from_tbl(OauthAccessTokens::Table)
                            .from_col(OauthAccessTokens::ClientId)
                            .from_col(OauthAccessTokens::Issuer)
                            .from_col(OauthAccessTokens::RedirectUri)
                            .to_tbl(OauthClientRedirectUris::Table)
                            .to_col(OauthClientRedirectUris::ClientId)
                            .to_col(OauthClientRedirectUris::Issuer)
                            .to_col(OauthClientRedirectUris::RedirectUri)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_tokens_family")
                            .from_tbl(OauthAccessTokens::Table)
                            .from_col(OauthAccessTokens::FamilyId)
                            .to_tbl(OauthRefreshTokenFamilies::Table)
                            .to_col(OauthRefreshTokenFamilies::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        for index in [
            Index::create()
                .name("uq_oauth_refresh_family_generation")
                .table(OauthRefreshTokens::Table)
                .col(OauthRefreshTokens::FamilyId)
                .col(OauthRefreshTokens::Generation)
                .unique()
                .to_owned(),
            Index::create()
                .name("idx_oauth_codes_expires_at")
                .table(OauthAuthorizationCodes::Table)
                .col(OauthAuthorizationCodes::ExpiresAt)
                .to_owned(),
            Index::create()
                .name("idx_oauth_codes_user_active")
                .table(OauthAuthorizationCodes::Table)
                .col(OauthAuthorizationCodes::UserId)
                .col(OauthAuthorizationCodes::ConsumedAt)
                .to_owned(),
            Index::create()
                .name("idx_oauth_tokens_expires_at")
                .table(OauthAccessTokens::Table)
                .col(OauthAccessTokens::ExpiresAt)
                .to_owned(),
            Index::create()
                .name("idx_oauth_tokens_user_active")
                .table(OauthAccessTokens::Table)
                .col(OauthAccessTokens::UserId)
                .col(OauthAccessTokens::RevokedAt)
                .to_owned(),
            Index::create()
                .name("idx_oauth_refresh_families_user")
                .table(OauthRefreshTokenFamilies::Table)
                .col(OauthRefreshTokenFamilies::UserId)
                .col(OauthRefreshTokenFamilies::RevokedAt)
                .to_owned(),
            Index::create()
                .name("idx_oauth_refresh_families_expiry")
                .table(OauthRefreshTokenFamilies::Table)
                .col(OauthRefreshTokenFamilies::AbsoluteExpiresAt)
                .to_owned(),
            Index::create()
                .name("idx_oauth_refresh_tokens_idle")
                .table(OauthRefreshTokens::Table)
                .col(OauthRefreshTokens::IdleExpiresAt)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(OauthDeviceAuthorizations::Table)
                    .col(ColumnDef::new(OauthDeviceAuthorizations::Id).string_len(64).not_null().primary_key())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::DeviceCodeDigest).binary_len(32).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::UserCodeDigest).binary_len(32).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::KeyId).string_len(64).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::ClientId).string_len(64).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::Issuer).string_len(2048).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::Resource).string_len(2048).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::Scope).string_len(512).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::Status).string_len(16).not_null().default("pending").check((
                        "ck_oauth_device_status",
                        Expr::col(OauthDeviceAuthorizations::Status).is_in(["pending", "approved", "denied", "consumed"]),
                    )))
                    .col(ColumnDef::new(OauthDeviceAuthorizations::UserId).string_len(64))
                    .col(ColumnDef::new(OauthDeviceAuthorizations::AuthVersion).big_integer().check((
                        "ck_oauth_device_auth_version",
                        Expr::col(OauthDeviceAuthorizations::AuthVersion).gte(0),
                    )))
                    .col(ColumnDef::new(OauthDeviceAuthorizations::CreatedAt).string_len(64).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::ExpiresAt).string_len(64).not_null())
                    .col(ColumnDef::new(OauthDeviceAuthorizations::IntervalSeconds).big_integer().not_null().check((
                        "ck_oauth_device_interval",
                        Expr::col(OauthDeviceAuthorizations::IntervalSeconds).gte(5),
                    )))
                    .col(ColumnDef::new(OauthDeviceAuthorizations::LastPollAt).string_len(64))
                    .col(ColumnDef::new(OauthDeviceAuthorizations::DecisionAt).string_len(64))
                    .col(ColumnDef::new(OauthDeviceAuthorizations::ConsumedAt).string_len(64))
                    .check((
                        "ck_oauth_device_code_digest_length",
                        Expr::cust("length(device_code_digest) = 32"),
                    ))
                    .check((
                        "ck_oauth_device_user_digest_length",
                        Expr::cust("length(user_code_digest) = 32"),
                    ))
                    .check((
                        "ck_oauth_device_state",
                        Expr::cust("(status = 'pending' AND user_id IS NULL AND auth_version IS NULL AND decision_at IS NULL AND consumed_at IS NULL) OR (status = 'denied' AND user_id IS NULL AND auth_version IS NULL AND decision_at IS NOT NULL AND consumed_at IS NULL) OR (status = 'approved' AND user_id IS NOT NULL AND auth_version IS NOT NULL AND decision_at IS NOT NULL AND consumed_at IS NULL) OR (status = 'consumed' AND user_id IS NOT NULL AND auth_version IS NOT NULL AND decision_at IS NOT NULL AND consumed_at IS NOT NULL)"),
                    ))
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_device_client")
                            .from_tbl(OauthDeviceAuthorizations::Table)
                            .from_col(OauthDeviceAuthorizations::ClientId)
                            .from_col(OauthDeviceAuthorizations::Issuer)
                            .to_tbl(OauthClients::Table)
                            .to_col(OauthClients::Id)
                            .to_col(OauthClients::Issuer)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_oauth_device_user")
                            .from_tbl(OauthDeviceAuthorizations::Table)
                            .from_col(OauthDeviceAuthorizations::UserId)
                            .to_tbl(Users::Table)
                            .to_col(Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        for index in [
            Index::create()
                .name("uq_oauth_device_user_code_digest")
                .table(OauthDeviceAuthorizations::Table)
                .col(OauthDeviceAuthorizations::UserCodeDigest)
                .unique()
                .to_owned(),
            Index::create()
                .name("idx_oauth_device_client_issuer")
                .table(OauthDeviceAuthorizations::Table)
                .col(OauthDeviceAuthorizations::ClientId)
                .col(OauthDeviceAuthorizations::Issuer)
                .to_owned(),
            Index::create()
                .name("idx_oauth_device_expires_at")
                .table(OauthDeviceAuthorizations::Table)
                .col(OauthDeviceAuthorizations::ExpiresAt)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(AuthOneTimeTokens::Table)
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::UserId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::Purpose)
                            .string_len(32)
                            .not_null()
                            .check((
                                "ck_auth_one_time_tokens_purpose",
                                Expr::col(AuthOneTimeTokens::Purpose)
                                    .is_in(["verify_email", "reset_password"]),
                            )),
                    )
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::CodeDigest)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::KeyId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::CreatedAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::ExpiresAt)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthOneTimeTokens::Attempts)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(AuthOneTimeTokens::ConsumedAt).string_len(64))
                    .check((
                        "ck_auth_one_time_tokens_digest_length",
                        Expr::cust("length(code_digest) = 32"),
                    ))
                    .check((
                        "ck_auth_one_time_tokens_expiry",
                        Expr::cust("expires_at > created_at"),
                    ))
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_auth_one_time_tokens_user")
                            .from_tbl(AuthOneTimeTokens::Table)
                            .from_col(AuthOneTimeTokens::UserId)
                            .to_tbl(Users::Table)
                            .to_col(Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        for index in [
            Index::create()
                .unique()
                .name("idx_auth_one_time_tokens_user_purpose")
                .table(AuthOneTimeTokens::Table)
                .col(AuthOneTimeTokens::UserId)
                .col(AuthOneTimeTokens::Purpose)
                .to_owned(),
            Index::create()
                .name("idx_auth_one_time_tokens_expires_at")
                .table(AuthOneTimeTokens::Table)
                .col(AuthOneTimeTokens::ExpiresAt)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        for index in [
            Index::create()
                .name("idx_oauth_tokens_family")
                .table(OauthAccessTokens::Table)
                .col(OauthAccessTokens::FamilyId)
                .to_owned(),
            Index::create()
                .name("idx_oauth_codes_redirect")
                .table(OauthAuthorizationCodes::Table)
                .col(OauthAuthorizationCodes::ClientId)
                .col(OauthAuthorizationCodes::Issuer)
                .col(OauthAuthorizationCodes::RegisteredRedirectUri)
                .to_owned(),
            Index::create()
                .name("idx_oauth_tokens_redirect")
                .table(OauthAccessTokens::Table)
                .col(OauthAccessTokens::ClientId)
                .col(OauthAccessTokens::Issuer)
                .col(OauthAccessTokens::RedirectUri)
                .to_owned(),
            Index::create()
                .name("idx_oauth_clients_issuer")
                .table(OauthClients::Table)
                .col(OauthClients::Issuer)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for table in [
            "auth_one_time_tokens",
            "oauth_device_authorizations",
            "oauth_access_tokens",
            "oauth_refresh_tokens",
            "oauth_refresh_token_families",
            "oauth_authorization_codes",
            "oauth_client_redirect_uris",
            "oauth_clients",
            "auth_sessions",
            "password_credentials",
            "users",
        ] {
            manager
                .drop_table(Table::drop().table(Alias::new(table)).to_owned())
                .await?;
        }
        Ok(())
    }
}

#[derive(DeriveIden)]
enum Users {
    Table,
    AuthVersion,
    CreatedAt,
    EmailDisplay,
    EmailNormalized,
    EmailVerifiedAt,
    Id,
    Role,
    Status,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum PasswordCredentials {
    Table,
    CreatedAt,
    PasswordHash,
    PepperKeyId,
    UpdatedAt,
    UserId,
}

#[derive(DeriveIden)]
enum AuthSessions {
    Table,
    AbsoluteExpiresAt,
    AuthVersion,
    AuthenticatedAt,
    CreatedAt,
    CsrfDigest,
    Id,
    IdleExpiresAt,
    KeyId,
    LastSeenAt,
    RevocationReason,
    RevokedAt,
    SecretDigest,
    Transport,
    UserAgent,
    UserId,
}

#[derive(DeriveIden)]
enum OauthClients {
    ApplicationType,
    ClientName,
    CreatedAt,
    GrantTypes,
    Id,
    Issuer,
    ResponseTypes,
    Scope,
    Table,
    TokenEndpointAuthMethod,
}

#[derive(DeriveIden)]
enum OauthClientRedirectUris {
    ClientId,
    Issuer,
    RedirectUri,
    Table,
}

#[derive(DeriveIden)]
enum OauthAuthorizationCodes {
    AuthVersion,
    ClientId,
    CodeChallenge,
    CodeChallengeMethod,
    ConsumedAt,
    CreatedAt,
    ExpiresAt,
    Id,
    IssuedAccessTokenId,
    Issuer,
    KeyId,
    RedirectUri,
    RegisteredRedirectUri,
    Resource,
    Scope,
    SecretDigest,
    Table,
    UserId,
}

#[derive(DeriveIden)]
enum OauthRefreshTokenFamilies {
    AbsoluteExpiresAt,
    AuthVersion,
    ClientId,
    CreatedAt,
    Id,
    Issuer,
    Resource,
    RevocationReason,
    RevokedAt,
    Scope,
    Table,
    UserId,
}

#[derive(DeriveIden)]
enum OauthRefreshTokens {
    CreatedAt,
    FamilyId,
    Generation,
    Id,
    IdleExpiresAt,
    KeyId,
    RevokedAt,
    RotatedAt,
    SecretDigest,
    Table,
}

#[derive(DeriveIden)]
enum OauthAccessTokens {
    AuthVersion,
    ClientId,
    CreatedAt,
    ExpiresAt,
    FamilyId,
    Id,
    Issuer,
    KeyId,
    RedirectUri,
    Resource,
    RevokedAt,
    Scope,
    SecretDigest,
    Table,
    UserId,
}

#[derive(DeriveIden)]
enum OauthDeviceAuthorizations {
    AuthVersion,
    ClientId,
    ConsumedAt,
    CreatedAt,
    DecisionAt,
    DeviceCodeDigest,
    ExpiresAt,
    Id,
    IntervalSeconds,
    Issuer,
    KeyId,
    LastPollAt,
    Resource,
    Scope,
    Status,
    Table,
    UserCodeDigest,
    UserId,
}

#[derive(DeriveIden)]
enum AuthOneTimeTokens {
    Attempts,
    CodeDigest,
    ConsumedAt,
    CreatedAt,
    ExpiresAt,
    Id,
    KeyId,
    Purpose,
    Table,
    UserId,
}
